=== BecsRobert/nkob5wWebXml_Lev/nkob5w_0301/mozi_ext.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mozi">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="film" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="rendezo">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                    <xs:attribute name="nev" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="szinesz">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                    <xs:attribute name="nev" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="iro">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="mufaj" type="xs:string" use="optional"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="rendezo" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="gyerek1">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                    <xs:attribute name="nev" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="gyerek2" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                    <xs:attribute name="nev" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="nev" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== BecsRobert/nkob5wWebXml_Lev/nkob5w_0301/nkob5w_mozi_ext.xml
<?xml version="1.0" encoding="UTF-8"?>
<mozi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mozi_ext.xsd">
    <film id="txn_nxm_2jb" mufaj="horror">
        <rendezo id="nzk_4xm_2jb" nev="alex"/>
        <szinesz id="u5q_4xm_2jb" nev="Madison_Ivy" />
        <iro id="trv_4xm_2jb"/>
    </film>
    <rendezo id="abc_4rf_5rt" nev="John_Doe">
        <gyerek1 id="h8z_5tr_3sa" nev="Bela"/>
        <gyerek2 id="g1y_5tr_m9u" nev="Jani"/>
    </rendezo>
</mozi>
