=== BecsRobert/nkob5wWebXml_Lev/nkob5w_0301/nkob5w_orarend.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="NKOB5W_orarend">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ora" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="kurzus" type="xs:string"/>
                            <xs:element name="idopont">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="datum" type="datumType"/>
                                        <xs:element name="nap" type="xs:string"/>
                                        <xs:element name="tol" type="timeType"/>
                                        <xs:element name="ig" type="timeType"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="helyszin" type="xs:string"/>
                            <xs:element name="oktato" type="xs:string"/>
                            <xs:element name="szak" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="tipus" type="tipusType" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="datumType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}\.\d{2}\.\d{2}\."/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="timeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-2][0-9]:[0-5][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tipusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="előadás"/>
            <xs:enumeration value="gyakorlat"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== BecsRobert/nkob5wWebXml_Lev/nkob5w_0301/nkob5w_orarend.xml
<?xml version="1.0" encoding="UTF-8"?>
<NKOB5W_orarend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nkob5w_orarend.xsd">
    <ora id="ora1" tipus="előadás">
        <kurzus>Webkönyvtárak</kurzus>
        <idopont>
            <datum>2025.03.01.</datum>
            <nap>Szombat</nap>
            <tol>13:30</tol>
            <ig>17:30</ig>
        </idopont>
        <helyszin>Kabar Tantermi</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Programtervező Informatikus Bsc</szak>
    </ora>
    <ora id="ora2" tipus="előadás">
        <kurzus>Komputergrafika és kékpfeldolgozás</kurzus>
        <idopont>
            <datum>2025.03.07.</datum>
            <nap>Péntek</nap>
            <tol>13:30</tol>
            <ig>17:30</ig>
        </idopont>
        <helyszin>Online</helyszin>
        <oktato>Fazekas Levente Áron</oktato>
        <szak>Programtervező Informatikus Bsc</szak>
    </ora>
    <ora id="ora3" tipus="előadás">
        <kurzus>Alkalmazás fejlesztése projekt labor II.</kurzus>
        <idopont>
            <datum>2025.03.08.</datum>
            <nap>Szombat</nap>
            <tol>09:00</tol>
            <ig>12:55</ig>
        </idopont>
        <helyszin>Kabar Tantermi</helyszin>
        <oktato>Perlaki Attila</oktato>
        <szak>Programtervező Informatikus Bsc</szak>
    </ora>
    <ora id="ora4" tipus="előadás">
        <kurzus>Szoftverjog és biztonságtechnika</kurzus>
        <idopont>
            <datum>2025.03.21.</datum>
            <nap>Péntek</nap>
            <tol>13:30</tol>
            <ig>17:30</ig>
        </idopont>
        <helyszin>Nincs megjelölve</helyszin>
        <oktato>Szekér Zoltán</oktato>
        <szak>Programtervező Informatikus Bsc</szak>
    </ora>
    <ora id="ora5" tipus="előadás">
        <kurzus>Alkalmazás fejlesztése projekt labor II.</kurzus>
        <idopont>
            <datum>2025.04.05.</datum>
            <nap>Szombat</nap>
            <tol>09:00</tol>
            <ig>12:55</ig>
        </idopont>
        <helyszin>Nincs megjelölve</helyszin>
        <oktato>Perlaki Attila</oktato>
        <szak>Programtervező Informatikus Bsc</szak>
    </ora>
    <ora id="ora6" tipus="előadás">
        <kurzus>Oktatás és gamifikáció, videójáték tanulmányok</kurzus>
        <idopont>
            <datum>2025.04.05.</datum>
            <nap>Szombat</nap>
            <tol>13:30</tol>
            <ig>17:30</ig>
        </idopont>
        <helyszin>Nincs megjelölve</helyszin>
        <oktato>Perlaki Attila</oktato>
        <szak>Programtervező Informatikus Bsc</szak>
    </ora>
    <ora id="ora7" tipus="előadás">
        <kurzus>Webkönyvtárak</kurzus>
        <idopont>
            <datum>2025.04.25.</datum>
            <nap>Péntek</nap>
            <tol>13:30</tol>
            <ig>17:30</ig>
        </idopont>
        <helyszin>Nincs megjelölve</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Programtervező Informatikus Bsc</szak>
    </ora>
    <ora id="ora8" tipus="előadás">
        <kurzus>Komputergrafika és képfeldolgozás</kurzus>
        <idopont>
            <datum>2025.05.09.</datum>
            <nap>Péntek</nap>
            <tol>13:30</tol>
            <ig>17:30</ig>
        </idopont>
        <helyszin>Nincs megjelölve</helyszin>
        <oktato>Fazekas Levente Áron</oktato>
        <szak>Programtervező Informatikus Bsc</szak>
    </ora>
    <ora id="ora9" tipus="előadás">
        <kurzus>Oktatás és gamifikáció, videójáték tanulmányok</kurzus>
        <idopont>
            <datum>2025.05.10.</datum>
            <nap>Szombat</nap>
            <tol>13:30</tol>
            <ig>17:30</ig>
        </idopont>
        <helyszin>Nincs megjelölve</helyszin>
        <oktato>Perlaki Attila</oktato>
        <szak>Programtervező Informatikus Bsc</szak>
    </ora>
    <ora id="ora10" tipus="előadás">
        <kurzus>Oktatás és gamifikáció, videójáték tanulmányok</kurzus>
        <idopont>
            <datum>2025.05.16.</datum>
            <nap>Péntek</nap>
            <tol>13:30</tol>
            <ig>17:30</ig>
        </idopont>
        <helyszin>Nincs megjelölve</helyszin>
        <oktato>Perlaki Attila</oktato>
        <szak>Programtervező Informatikus Bsc</szak>
    </ora>
</NKOB5W_orarend>
